/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Librarian;

import Business.Business;
import Material.Book;

/**
 *
 * @author tianshiyun
 */
public class BookJPanel extends javax.swing.JPanel {
    Business business;

    /**
     * Creates new form BookJPanel
     */
    public BookJPanel() {
        initComponents();
    }
    
    public BookJPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        languageBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pages = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        binding = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        serial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Available = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 43, -1, -1));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 43, 141, 31));

        jLabel2.setText("Genre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 109, -1, -1));
        add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 109, 141, 32));

        jLabel3.setText("Author");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 174, -1, -1));
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 181, 141, 32));

        jLabel4.setText("Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 249, -1, -1));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 256, 141, 31));

        jLabel5.setText("Language");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 329, -1, -1));

        languageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Chinese", "Japanese", " " }));
        add(languageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 328, 94, 33));

        jLabel6.setText("No. of Pages");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 409, -1, -1));
        add(pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 408, 141, 34));

        jLabel7.setText("Type of Binding");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 476, -1, -1));
        add(binding, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 474, 140, 36));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 629, -1, -1));

        jLabel8.setText("Serial Number");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 535, -1, -1));

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 6, -1, -1));

        jTextField2.setText("jTextField2");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 6, -1, -1));

        jTextField3.setText("jTextField3");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 6, -1, -1));
        add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 140, 30));

        jLabel9.setText("Availability");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        Available.setEditable(false);
        Available.setText("Available");
        add(Available, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Book book = new Book();
        String n = name.getText();
        book.setName(n);
        String g = genre.getText();
        book.setGenre(g);
        String a = author.getText();
        book.setAuthor(a);
        String d = date.getDate().toString();
        book.setDate(d);
        String l = (String)languageBox.getSelectedItem();
        book.setLanguage(l);
        String p = pages.getText();
        book.setPageNo(ABORT);
        String b = binding.getText();
        book.setBinding(b);
        String seri = serial.getText();
        book.setSerialNumber(seri);
        Boolean bo = Boolean.valueOf(Available.getText());
        book.setAvailability(bo);
        book.setType("book");
        
        this.business.getBookDirectory().getBookDirectory().add(book);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Available;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField author;
    private javax.swing.JTextField binding;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> languageBox;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pages;
    private javax.swing.JTextField serial;
    // End of variables declaration//GEN-END:variables
}
