/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Librarian;

import Business.Business;
import Material.Magazine;

/**
 *
 * @author tianshiyun
 */
public class MagazineJPanel extends javax.swing.JPanel {
    Business business;
    /**
     * Creates new form MaterialJPanel
     */
    public MagazineJPanel() {
        initComponents();
    }
    
    public MagazineJPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        serial = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        available = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 45, -1, -1));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 38, 152, 32));

        jLabel3.setText("Company name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 118, -1, -1));
        add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 108, 180, 30));

        jLabel4.setText("Issue Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 190, -1, -1));

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "weekly", "fortnightly", " " }));
        add(typeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 184, 85, 29));

        jLabel2.setText("Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel5.setText("Availability");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setText("Serial Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));
        add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 220, 30));

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        available.setEditable(false);
        available.setText("Available");
        add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Magazine m = new Magazine();
        
        String se = serial.getText();
        m.setSerialNumber(se);
        String n = name.getText();
        m.setName(n);
        String date = jDateChooser1.getDate().toString();
        m.setDate(date);
        Boolean avai = Boolean.valueOf(available.getText());
        m.setAvailability(avai);
        String ty = (String)typeBox.getSelectedItem();
        m.setIssueType(ty);
        m.setType("Magazine");
        String com = companyName.getText();
        m.setCompany(com);
        
        this.business.getMagazineDirectory().getMagazineDirectory().add(m);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField available;
    private javax.swing.JTextField companyName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField serial;
    private javax.swing.JComboBox<String> typeBox;
    // End of variables declaration//GEN-END:variables
}
