/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tianshiyun
 */
public class CreatJPanel extends javax.swing.JPanel {
    Person person;
    ArrayList <Person> personList;
    Recipe recipeItem;
    String path;
    
    
    /**
     * Creates new form CreatJPanel
     */
    public CreatJPanel() {
        initComponents();
        this.person = new Person();
        
        
    }
    public CreatJPanel(ArrayList <Person> personList){
        initComponents();
        
        this.person = new Person();
        this.personList = personList;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        servingText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        glutenFreeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        difficultLevelText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ingredientsText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        categoryText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eMailText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        Picture = new javax.swing.JLabel();
        Browse = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        userName.setForeground(new java.awt.Color(51, 51, 51));
        userName.setText("User Name");

        Save.setBackground(new java.awt.Color(245, 72, 122));
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Recipe");

        jLabel2.setText("Name");

        jLabel3.setText("No. of Servings");

        jLabel4.setText("Gluten Free");

        glutenFreeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        glutenFreeComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                glutenFreeComboBoxPropertyChange(evt);
            }
        });

        jLabel5.setText("Difficult Level");

        jLabel6.setText("No. of Ingredients");

        jLabel7.setText("Category of Food");

        jLabel8.setText("Descriptiion");

        jLabel9.setText("E-mail");

        jLabel10.setText("Phone");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        Picture.setText("jLabel12");

        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(descriptionText)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(difficultLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(glutenFreeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(servingText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(userName)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(userNameTxt)
                                                .addComponent(eMailText)
                                                .addComponent(phoneText, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ingredientsText, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(210, 210, 210))))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Browse)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userName)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(eMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Browse)
                        .addGap(14, 14, 14)))
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(servingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(glutenFreeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(difficultLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ingredientsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(addButton)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void glutenFreeComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_glutenFreeComboBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_glutenFreeComboBoxPropertyChange

    
   
    
     
    
    public  Boolean isExist(String name){
        
        Boolean a = true;
        name = userNameTxt.getText();
        for(Person p:personList){
            if(name.equals(p.getUserName())){
             a=true;
        }else{                
                a = false;
            }                
            
    }return a;
}
    
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String userN = userNameTxt.getText();
        String eMail = eMailText.getText();
        String phone = phoneText.getText();
        Pattern pattern;
        String emailValidate = "^ [a-zA-Z0-9_+&*-]+ (?:11. [a-zA-Z0-9_+&*-]+) *@(?: [a-zA-Z0-9-]+|1.)+ [a-zA-Z]{2,77}$";       
        if(userNameTxt.getText().isEmpty() || eMailText.getText().isEmpty() || phoneText.getText().isEmpty() ){
           JOptionPane.showMessageDialog(this, "Cannot be empty");
            }if(isExist(userNameTxt.getText())== false){
                JOptionPane.showMessageDialog(this, "User Name has already existed");
                }else{
                    this.person.setUserName(userN);
                    if(!phoneText.getText().matches("[0-9]*")){
                    JOptionPane.showMessageDialog(this, "Format is wrong!");
                    return;
                    }
                    this.person.setPhone(Long.valueOf(phone));
             
                 
                    pattern=Pattern.compile (emailValidate);
                    if(pattern.matcher (eMail).matches ()){
                    System.out.println (1);
                     }
                        else{
                            JOptionPane.showMessageDialog(null,"Email is not correct'");
                            return;
                            }
                     String nameValidate = "^[A-Za-z]+$";
                    pattern=Pattern.compile (nameValidate);
                    if (pattern.matcher (userN) .matches () ){
        
                    }
                    else{JOptionPane.showMessageDialog(null,"userName is not correct");
                    this.person.seteMail(eMail);   }    
                    
        
        
                    personList.add(this.person);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        String categoryTxt = categoryText.getText();
        String desciptionTxt = descriptionText.getText();
        
        if(!difficultLevelText.getText().matches("[0-9]*(.[0-9]*)?")){
           JOptionPane.showMessageDialog(this, "Format is wrong!");
           return;
        }
        Double difficultLV = Double.parseDouble(difficultLevelText.getText());
        
        Boolean glutenF = Boolean.parseBoolean(glutenFreeComboBox.getActionCommand());
        String ingredientsTxt = ingredientsText.getText();
        int noOfServingTxt = Integer.valueOf(servingText.getText());
        if(!servingText.getText().matches("[0-9]*")){
           JOptionPane.showMessageDialog(this, "Format is wrong!");
           return;
        }
        String nameTxt = nameText.getText();
        
        Recipe recipe1 = new Recipe(nameTxt,noOfServingTxt, glutenF, difficultLV, ingredientsTxt, categoryTxt, desciptionTxt);
        this.person.getRecipeList().add(recipe1);
        
        recipe1.setPath(path);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MAGES", "png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(filter); 
        int showOpenDialogue = browseImageFile.showOpenDialog((null));
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            path=selectedImagePath;
            JOptionPane.showMessageDialog(null, selectedImagePath);
            ImageIcon imageI = new ImageIcon(selectedImagePath);
            
            Image image = imageI.getImage().getScaledInstance(Picture.getWidth(), Picture.getHeight(), Image.SCALE_SMOOTH);
            Picture.setIcon(new ImageIcon(image));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_BrowseActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton Save;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField categoryText;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField difficultLevelText;
    private javax.swing.JTextField eMailText;
    private javax.swing.JComboBox<String> glutenFreeComboBox;
    private javax.swing.JTextField ingredientsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTextField servingText;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
