/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package huskycard;
import Model.Address;
import Model.Person;
import Model.Contact;


/**
 *
 * @author tianshiyun
 */
public class Husky_JFrame extends javax.swing.JFrame {
    private Person person;
    private Address address;
    private Contact contact;
    /**
     * Creates new form Husky_JFrame
     */
    public Husky_JFrame() {
        initComponents();
        this.person= new Person();
        this.address = new Address();
        this.contact = new Contact();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void display(){
        
        
        viewName.setText("Name: " + this.person.getFirstName()+this.person.getLastName());
        viewNUID.setText("NUID: " + this.person.getiD());
        viewCollege.setText("College: " + this.person.getCollege());
        labelContactInformation.setText("Contact Information");
        viewOfficeEmail.setText("Office E-mail: " + this.person.getContact().getOfficeEmail());
        viewPersonalEmail.setText("Personal E-mail: " + this.person.getContact().getPersonalEmail());
        viewOfficePhone.setText("Office Phone: " + this.person.getContact().getOfficePhone());
        viiewPersonalPhone.setText("Personal Phone: " + this.person.getContact().getPersonalPhone());
        labelAddress.setText("Address");
        viewPermanantAddress.setText("Permanant Address: " + this.address.getpStreetName()+ this.address.getpAptNo() + this.address.getpCityState() + this.address.getpZipcode());
        viewCurrentAddress.setText("Current Address; " + this.address.getcStreetName()+ this.address.getcAptNo() + this.address.getcCityState() + this.address.getcZipcode());
        
        
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        left = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        NUID_ = new javax.swing.JLabel();
        NUID = new javax.swing.JTextField();
        CollegeName = new javax.swing.JLabel();
        collegeName = new javax.swing.JTextField();
        ContactInformation = new javax.swing.JLabel();
        officeEmail = new javax.swing.JTextField();
        PersonalPhone = new javax.swing.JLabel();
        OfficePhone = new javax.swing.JLabel();
        personalPhone = new javax.swing.JTextField();
        OfficeEmail = new javax.swing.JLabel();
        officePhone = new javax.swing.JTextField();
        PersonalEmail = new javax.swing.JLabel();
        personalEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentStreetName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        currentAptNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        currentCityState = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        currentZipCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        permanantStreetName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        permanantAptNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        permanantCityState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        permanantZipCode = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        viewName = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewCollege = new javax.swing.JLabel();
        labelContactInformation = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viiewPersonalPhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        viewCurrentAddress = new javax.swing.JLabel();
        viewPermanantAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        left.setBackground(new java.awt.Color(255, 153, 153));

        FirstName.setText("FirstName");

        LastName.setBackground(new java.awt.Color(153, 153, 255));
        LastName.setText("LastName");

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        NUID_.setText("NUID");

        NUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDActionPerformed(evt);
            }
        });

        CollegeName.setText("College Name");

        collegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeNameActionPerformed(evt);
            }
        });

        ContactInformation.setText("Contact Information:");

        officeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeEmailActionPerformed(evt);
            }
        });

        PersonalPhone.setText("Personal Phone");

        OfficePhone.setText("Office Phone");

        OfficeEmail.setText("Office E-mail");

        officePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officePhoneActionPerformed(evt);
            }
        });

        PersonalEmail.setText("Personal E-mail");

        personalEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Cunrrent Address:");

        jLabel2.setText("Street Name:");

        jLabel3.setText("Apt. No:");

        jLabel4.setText("City/State");

        jLabel5.setText("ZipCode");

        jLabel6.setText("Permanent Address:");

        jLabel7.setText("Street Name:");

        jLabel8.setText("Apt. No");

        jLabel9.setText("City/State");

        jLabel10.setText("ZipCode");

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(leftLayout.createSequentialGroup()
                        .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftLayout.createSequentialGroup()
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactInformation)
                                    .addGroup(leftLayout.createSequentialGroup()
                                        .addComponent(FirstName)
                                        .addGap(34, 34, 34)
                                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(leftLayout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(Save))
                                    .addGroup(leftLayout.createSequentialGroup()
                                        .addComponent(NUID_)
                                        .addGap(63, 63, 63)
                                        .addComponent(NUID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CollegeName)
                                    .addComponent(LastName)))
                            .addGroup(leftLayout.createSequentialGroup()
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OfficePhone)
                                    .addComponent(OfficeEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(leftLayout.createSequentialGroup()
                                        .addComponent(officePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PersonalEmail)
                                            .addComponent(PersonalPhone)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                                        .addComponent(officeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftLayout.createSequentialGroup()
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(personalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(leftLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(collegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE))))
                    .addGroup(leftLayout.createSequentialGroup()
                        .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(leftLayout.createSequentialGroup()
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(57, 57, 57)
                                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentStreetName)
                                    .addComponent(currentAptNo)
                                    .addComponent(currentCityState)
                                    .addComponent(currentZipCode)
                                    .addComponent(permanantStreetName)
                                    .addComponent(permanantAptNo)
                                    .addComponent(permanantCityState)
                                    .addComponent(permanantZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUID_)
                    .addComponent(NUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CollegeName)
                    .addComponent(collegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ContactInformation)
                .addGap(18, 18, 18)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficePhone)
                    .addComponent(PersonalPhone)
                    .addComponent(personalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficeEmail)
                    .addComponent(officeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonalEmail)
                    .addComponent(personalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(currentAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(permanantStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permanantAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(permanantCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(permanantZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(27, 27, 27))
        );

        jSplitPane1.setLeftComponent(left);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 0, 102));

        viewName.setText("Name");

        viewNUID.setText("NUID");

        viewCollege.setText("College");

        labelContactInformation.setText("Contact Information");

        viewOfficePhone.setText("Office Phone");

        viiewPersonalPhone.setText("Personal Phone");

        viewOfficeEmail.setText("Office E-mail");

        viewPersonalEmail.setText("Personal E-mail");

        labelAddress.setText("Address");

        viewCurrentAddress.setText("Current Address");

        viewPermanantAddress.setText("Permanant Address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPermanantAddress)
                    .addComponent(viewCurrentAddress)
                    .addComponent(labelAddress)
                    .addComponent(labelContactInformation)
                    .addComponent(viewCollege)
                    .addComponent(viewNUID)
                    .addComponent(viewName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewOfficePhone)
                            .addComponent(viewOfficeEmail))
                        .addGap(175, 175, 175)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPersonalEmail)
                            .addComponent(viiewPersonalPhone))))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(viewName)
                .addGap(18, 18, 18)
                .addComponent(viewNUID)
                .addGap(18, 18, 18)
                .addComponent(viewCollege)
                .addGap(18, 18, 18)
                .addComponent(labelContactInformation)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewOfficePhone)
                    .addComponent(viiewPersonalPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewOfficeEmail)
                    .addComponent(viewPersonalEmail))
                .addGap(18, 18, 18)
                .addComponent(labelAddress)
                .addGap(18, 18, 18)
                .addComponent(viewCurrentAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPermanantAddress)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lastNameActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
           // TODO add your handling code here:
           String fName = firstName.getText();
           String lName = lastName.getText();
           String nuid = NUID.getText();
           String coName = collegeName.getText();
           String oPhone = officePhone.getText();
           String pPhone = personalPhone.getText();
           String oEmail = officeEmail.getText();
           String pEmail = personalEmail.getText();
           
           String cStreetName = currentStreetName.getText();
           String cAptNo = currentAptNo.getText();
           String cCityState = currentCityState.getText();
           String cZipCode = currentZipCode.getText();
           
           String pStreetName = permanantStreetName.getText();
           String pAptNo = permanantAptNo.getText();
           String pCityState = permanantCityState.getText();
           String pZipCode = permanantZipCode.getText();
           
           
           
           
           this.person.setFirstName(fName);
           this.person.setLastName(lName);
           this.person.setCollege(coName);
           this.person.setiD(nuid);
           this.person.setContact(contact);
           this.address.setcAptNo(cAptNo);
           this.address.setcCityState(cCityState);
           this.address.setcStreetName(cStreetName);
           this.address.setcZipcode(cZipCode);
           this.address.setpAptNo(pAptNo);
           this.address.setpCityState(pCityState);
           this.address.setpStreetName(pStreetName);
           this.address.setpZipcode(pZipCode);
           this.contact.setOfficeEmail(oEmail);
           this.contact.setOfficePhone(oPhone);
           this.contact.setPersonalEmail(pEmail);
           this.contact.setPersonalPhone(pPhone);
           
           
           
           display();
           
                 
           
    }//GEN-LAST:event_SaveActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void NUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDActionPerformed

    private void collegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeNameActionPerformed

    private void officeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officeEmailActionPerformed

    private void officePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officePhoneActionPerformed

    private void personalEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Husky_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CollegeName;
    private javax.swing.JLabel ContactInformation;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField NUID;
    private javax.swing.JLabel NUID_;
    private javax.swing.JLabel OfficeEmail;
    private javax.swing.JLabel OfficePhone;
    private javax.swing.JLabel PersonalEmail;
    private javax.swing.JLabel PersonalPhone;
    private javax.swing.JButton Save;
    private javax.swing.JTextField collegeName;
    private javax.swing.JTextField currentAptNo;
    private javax.swing.JTextField currentCityState;
    private javax.swing.JTextField currentStreetName;
    private javax.swing.JTextField currentZipCode;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelContactInformation;
    private javax.swing.JTextField lastName;
    private javax.swing.JPanel left;
    private javax.swing.JTextField officeEmail;
    private javax.swing.JTextField officePhone;
    private javax.swing.JTextField permanantAptNo;
    private javax.swing.JTextField permanantCityState;
    private javax.swing.JTextField permanantStreetName;
    private javax.swing.JTextField permanantZipCode;
    private javax.swing.JTextField personalEmail;
    private javax.swing.JTextField personalPhone;
    private javax.swing.JLabel viewCollege;
    private javax.swing.JLabel viewCurrentAddress;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermanantAddress;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viiewPersonalPhone;
    // End of variables declaration//GEN-END:variables
}
