/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.Insurance;
import Model.Owner;
import Model.Pet;
import Model.Vaccination;
import java.util.ArrayList;

/**
 *
 * @author tianshiyun
 */
public class CreateJPanel extends javax.swing.JPanel {

    
    Owner owner;
    private Pet pet;
    Vaccination vaccination;
    Insurance insurance;
    Business business;
    ArrayList<Vaccination> vaccineList ;
    
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
        
        
    }
    
    public CreateJPanel(Business business) {
        initComponents();
        this.owner = owner;
        this.pet = pet;
        this.vaccination= vaccination;
        this.insurance = insurance;
        this.business = business;
        this.vaccineList = vaccineList;
        for(Insurance ins:business.getInsurancePlan()){
            insuranceComboBox.addItem(ins.getName());
        }
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        applicationID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        petName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        petAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        petGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        breed = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vaccineName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        courseCompleted = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        insuranceComboBox = new javax.swing.JComboBox<>();
        createButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        petType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Application ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));
        add(applicationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, 30));

        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, 20));

        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, 20));

        jLabel4.setText("Application Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel5.setText("Pet Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        add(petName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 170, 20));

        jLabel6.setText("Pet Age");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));
        add(petAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel7.setText("Pet Gender");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        add(petGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 120, 20));

        jLabel8.setText("Breed");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));
        add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 120, 20));

        jLabel9.setText("Vaccine Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));
        add(vaccineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        jLabel10.setText("Course Completed (ture/false)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));
        add(courseCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jLabel11.setText("Insurance Plan");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        insuranceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceComboBoxActionPerformed(evt);
            }
        });
        add(insuranceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, -1, -1));

        jLabel12.setText("Pet type");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));
        add(petType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 120, -1));

        jButton1.setText("Add vaccination");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        Long id = Long.valueOf(applicationID.getText());
        String firstN = firstName.getText();
        String lastN = lastName.getText();
        String date = jDateChooser1.getDateFormatString();
        System.out.println(date);
        
        String petN = petName.getText();
        int age = Integer.valueOf(petAge.getText());
        String gender = petGender.getText();
        String type = petType.getText();
        String breedsS = breed.getText();
        
        
        
        
        Insurance insurance = new Insurance();
        insurance = selectInsurance();
        
        Pet pet = new Pet(petN,age,gender,type,breedsS,vaccineList,insurance);
        //Long id, String firstName, String lastName, Pet pet
        Owner owner = new Owner(id,firstN,lastN,date,pet);
        business.getOwnerList().add(owner);
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    
    public Insurance selectInsurance(){
        String insO = (String)insuranceComboBox.getSelectedItem();
        Insurance insurance = new Insurance();
        for(Insurance ins:business.getInsurancePlan()){
            if(insO.equals(ins.getName())){
                insurance = ins;
            }
        }return insurance;
    }
    private void insuranceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceComboBoxActionPerformed
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String n = vaccineName.getText();
        Boolean courseCom = Boolean.valueOf(courseCompleted.getText());
            Vaccination v = new Vaccination(n, courseCom );
            vaccineList.add(v);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applicationID;
    private javax.swing.JTextField breed;
    private javax.swing.JTextField courseCompleted;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox<String> insuranceComboBox;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField petAge;
    private javax.swing.JTextField petGender;
    private javax.swing.JTextField petName;
    private javax.swing.JTextField petType;
    private javax.swing.JTextField vaccineName;
    // End of variables declaration//GEN-END:variables
}
